#!/bin/bash

bold=$(tput bold)
red=$(tput setaf 1)
yel=$(tput setaf 3)
end=$(tput sgr 0)

# Define Hardware platform
platform=`uname -i`

# Checking platforms
if [[ $platform == "x86_64" ]]; then
platform="amd64"
elif [[ $platform == "armv7l" ]]; then
chipset="armv7l"
platform="arm"
fi


echo "$bold $red Installing Dependencies $end"

echo "$bold $yel   > Installing Scilab... $end"
	sudo apt-get install scilab

echo "$bold $yel   > Installing python-numpy... $end"
	sudo apt-get install python-numpy

#echo "Installing python"
echo "$bold $red Installing sciscipy $end"
	./setup.py build

# For Debian/Ubuntu based OSes
sudo ./setup.py install --install-layout=deb --record installed_files.txt

echo "$bold $red Setting up variables $end"
	s2pconf=/etc/ld.so.conf.d/sciscipy.conf
	
	# Remove existing sciscipy.conf	
	sudo rm $s2pconf

	sudo bash -c "echo '/usr/lib/scilab' >> $s2pconf"
	sudo bash -c "echo '/usr/lib/jvm/default-java/jre/lib/$platform/native_threads' >> $s2pconf"
	sudo bash -c "echo '/usr/lib/jvm/default-java/jre/lib/$platform/' >> $s2pconf"
	sudo bash -c "echo '/usr/lib/jvm-/efault-java/jre/lib/$platform/server' >> $s2pconf"

	env=/etc/environment
	sudo bash -c "echo 'export PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games' >> $env"
	sudo bash -c "echo 'export SCI=/usr/share/scilab' >> $env"
	sudo bash -c "echo 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/scilab:/usr/lib/jvm/java-6-openjdk-$platform/jre/lib/$platform/server/:/usr/lib/jvm/java-6-openjdk/jre/lib/$platform/native_threads/:/usr/local/lib' >> $env"
	source $env
# Testing
echo "$bold $red Testing... $end"
	CURRENT_PATH=`pwd`
	export PYTHONPATH="$CURRENT_PATH/build/lib.linux-x86_64-2.7/"
	./setup.py test
